apiVersion: skaffold/v2beta29
kind: Config

build:
  artifacts:
  - image: rg.fr-par.scw.cloud/tongli/backend
    context: backend
    docker:
      buildArgs:
        ENV: production
  - image: rg.fr-par.scw.cloud/tongli/migration
    context: migration
    docker:
      buildArgs:
        ENV: production
  - image: rg.fr-par.scw.cloud/tongli/frontend
    context: frontend
    docker:
      buildArgs:
        ENV: production

profiles:
  - name: cloud
    deploy:
      kustomize:
        paths:
          - k8s/cloud
  - name: dev
    deploy:
      kustomize:
        paths:
          - k8s/dev
