apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
  - port: 3000
  type: LoadBalancer
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: rg.fr-par.scw.cloud/tongli/backend
        ports:
        - containerPort: 3000
        env:
        - name: DB_VENDOR
          value: "postgres"
        - name: DB_ADDR
          valueFrom: { secretKeyRef: { name: database-pguser-database, key: host } }
        - name: DB_PORT
          valueFrom: { secretKeyRef: { name: database-pguser-database, key: port } }
        - name: DB_DATABASE
          valueFrom: { secretKeyRef: { name: database-pguser-database, key: dbname } }
        - name: DB_USER
          valueFrom: { secretKeyRef: { name: database-pguser-database, key: user } }
        - name: DB_PASSWORD
          valueFrom: { secretKeyRef: { name: database-pguser-database, key: password } }
        - name: DB_COMMENTS_TABLE
          value: "comments"
        - name: DB_USERS_TABLE
          value: "users"
      imagePullSecrets:
        - name: registry-secret
