apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - port: 3000
  type: LoadBalancer
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: rg.fr-par.scw.cloud/tongli/frontend
        ports:
        - containerPort: 3000
        env:
        - name: API_BASE_URL
          value: "http://backend:3000"
      imagePullSecrets:
        - name: registry-secret
